events {}
http {
    access_log off;
    server {
        listen 443 ssl;
        server_name localhost;
        ssl_certificate /etc/nginx/tls/master.crt;
        ssl_certificate_key /etc/nginx/tls/master.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        client_max_body_size 10m;

        location ~ ^/openmrs/moduleServlet/synchronizationmr/(patientSync|encounterSync|orderSync)$ {
            proxy_pass http://host.docker.internal:8080;
            proxy_set_header Host localhost:8443;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Port 8443;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Forwarded "";
            proxy_read_timeout 120s;
        }
        location / { return 404; }
    }
}
